---
title: "Tracker electoral"
output: 
  flexdashboard::flex_dashboard:
    theme: readable
    orientation: rows
---

```{r setup, include=FALSE}
knitr::opts_knit$set(self.contained = T)
#source("procesamiento_graficos.R")
library(readr)
```

Resultados encuestas {data-icon="fa-chart-bar"}
=====================================  

Row {.tabset .tabset-fade}
-------------------------------------
### Resultados sin ponderaciones
<iframe frameBorder="0" src="img/sin_margen_error.html" width="100%" height="100%" allowtransparency="true"></iframe>

### Resultados con ponderaciones
<iframe width="983" height="452" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRrkrs91NFfjIgL76DyQATvjAsaklmOxLkxS1y4cJorP8Bk92wmDxFprhHIxgi-eGeBotlHD3_W8mpx/pubchart?oid=1247236956&amp;format=interactive"></iframe>

Base de datos {data-icon="fa-database"}
=====================================  
<br>
<br>
<br>
<br>
<br>
<br>
<center><h2>Acceda a la base de datos haciendo click en el ícono</h2></center><br>
<br>
<br>
<center><a href="https://docs.google.com/spreadsheets/d/1h8yQCUJCUqaIsVPPWz6TDSx5wbl8-g-ksAaaoxT6qb4/edit#gid=357606713"><i class="fa fa-database fa-4x"></i></a></center>

Metodología {data-icon="fa-pencil-alt"}
=====================================  

<a href="https://twitter.com/rafa_lopezv"><i class="fa fa-twitter fa-xs"></i></a>

Sobre encuestadoras {data-icon="fa-list-alt"}
=====================================  

Sobre el proyecto {data-icon="fa-sticky-note"}
=====================================  

<h2>El presente proyecto busca recopilar información relevante para el proceso electoral en Bolivia de cara a las elecciones generales del 20 de octubre de 2019. En su primera fase, el proyecto procura reunir las cifras de todas las encuestas electorales publicadas en Bolivia desde noviembre de 2016. Considerando que a la fecha se publicaron y difundieron datos en más de 10 medios, producidos por 7 encuestadoras, el proyecto busca comparar los datos.</h2>




